### PR TITLE
chrome extension added

### PR DESCRIPTION
**Pull request by sumitbaroniya**

### CODE REVIEW

**Comment by DevoAbhi** [comment]
Sorry, I could not understand this PR.
Have you made a chrome extension for jokes?

**Comment by sumitbaroniya** [comment]
yes

**Comment by DevoAbhi** [comment]
Sorry, but this issue was not to create a random chrome extension but to create an extension for the website. 
If you want you can continue with creating an extension for the website, or look for other issues.

Thank you.

**Comment by sumitbaroniya** [comment]
Ok, i will create an extension for the website. Sorry, I thought issue need to make random chrome extension .

**Comment by DevoAbhi** [comment]
> Ok, i will create an extension for the website. Sorry, I thought issue need to make random chrome extension .

Ok, that would be great.

**Pull request closed without merging**
